// <auto-generated />
using System;
using API_Games_Genres.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API_Games_Genres.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("API_Games_Genres.Models.Player", b =>
                {
                    b.Property<int>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlayerId"), 1L, 1);

                    b.Property<int>("BiggestPrizeWon")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MoneyWon")
                        .HasColumnType("int");

                    b.Property<string>("NickName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfTournamentsPlayed")
                        .HasColumnType("int");

                    b.Property<int>("StartedPlaying")
                        .HasColumnType("int");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("PlayerId");

                    b.HasIndex("TeamId");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            PlayerId = 1,
                            BiggestPrizeWon = 300,
                            FirstName = "Jouda",
                            LastName = "Špatný",
                            MoneyWon = 500,
                            NickName = "Aldra1n",
                            NumberOfTournamentsPlayed = 3,
                            StartedPlaying = 2013,
                            TeamId = 1
                        },
                        new
                        {
                            PlayerId = 2,
                            BiggestPrizeWon = 8000,
                            FirstName = "Jarmil",
                            LastName = "Holohlavý",
                            MoneyWon = 10000,
                            NickName = "Filadelfie",
                            NumberOfTournamentsPlayed = 15,
                            StartedPlaying = 2015,
                            TeamId = 1
                        });
                });

            modelBuilder.Entity("API_Games_Genres.Models.Team", b =>
                {
                    b.Property<int>("TeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeamId"), 1L, 1);

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("MembersCount")
                        .HasColumnType("int");

                    b.Property<int>("MoneyWon")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Place")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TeamId");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            TeamId = 1,
                            CreationDate = new DateTime(2022, 4, 11, 21, 14, 40, 882, DateTimeKind.Local).AddTicks(878),
                            MembersCount = 5,
                            MoneyWon = 5000,
                            Name = "Liquid",
                            Owner = "Pepek",
                            Place = "Praha"
                        },
                        new
                        {
                            TeamId = 2,
                            CreationDate = new DateTime(2022, 4, 11, 21, 14, 40, 882, DateTimeKind.Local).AddTicks(936),
                            MembersCount = 8,
                            MoneyWon = 100,
                            Name = "MeXXeSSovi Kamarádi",
                            Owner = "NeeX",
                            Place = "Brno"
                        });
                });

            modelBuilder.Entity("API_Games_Genres.Models.Player", b =>
                {
                    b.HasOne("API_Games_Genres.Models.Team", "Team")
                        .WithMany("Players")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("API_Games_Genres.Models.Team", b =>
                {
                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
